services:

  postgres:
    image: postgres:16
    container_name: smartqueue-postgres
    restart: always

    environment:
      POSTGRES_DB: smartqueue
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - smartqueue-network

  redis:
    image: redis:7
    container_name: smartqueue-redis
    restart: always

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    networks:
      - smartqueue-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: smartqueue-rabbitmq
    restart: always

    ports:
      - "5672:5672"
      - "15672:15672"

    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

    networks:
      - smartqueue-network

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:

networks:
  smartqueue-network:
    driver: bridge